name: approval

on:
  push:
    branches: ["**"]

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: provision
        id: provision
        run: |
          echo "provision aaa"

  deploy-development:
    runs-on: ubuntu-latest
    needs: provision
    environment:
      name: development
      url: http://example.com/
    steps:
      - name: deploy development
        id: deploy-development
        run: |
          echo "deploy aaa"
