name: approval

on:
  push:
    branches: [test1]
  pull_request:
    branches: [test1]

jobs:
  provision:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: provision
        id: provision
        # PRへのコメントをpostしたい
        run: |
          echo "provision aaa"

  after:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: development
      url: http://example.com/
    steps:
      - name: after
        id: after
        run: |
          echo "build aaa"
